# ISA616-Project2-Group-8

# Problem

Currently there is uncertainty in the prediction of post-graduation salaries from the Farmer School of Business. This is because of little understanding in which variables are significant, a continuous flow of data with no streamlined analysis process, and a struggle to create insight with these data sets. Addressing these points would allow for a more efficient process in data analysis that would benefit FSB's brand and opportunities.

# Objective

Our objective is to provide the Farmer School of Business (FSB) with a comprehensive data analysis solution that helps improve their rankings, strengthen brand positioning, and enhance overall student outcomes. The primary focus is on developing a clean, understandable dataset that accurately reflects post-college success metrics, such as job placement and salary data.

# Solution 
Our solutions are as follows
* Develop an interactive dashboard that consolidates key metrics and allows FSB to access and present real-time data to stakeholders
* Provide a comparative analysis that benchmarks FSB’s performance against competitor institutions, helping to identify strengths and areas of improvement in program offerings
* Establish feedback loop with stakeholders to continuously refine data collection, reporting, and communication processes


We plan to implement the following solutions by cleaning our data for use, this includes recoding, measuring the importance of, and preforming analysis of variables in R_Studio.

# Zip Folder Contents

* SS_2019_2021.csv                  Origonal Dataset
* clean_student_success_data.csv    Clean Dataset
* Business Value Proposition.png    BVP diagram
*
